export const CHATS_LIST_REQUEST = "CHATS_LIST_REQUEST";
export const CHATS_LIST_SUCCESS = "CHATS_LIST_SUCCESS";
export const CHATS_LIST_FAIL = "CHATS_LIST_FAIL";

export const ADD_CHAT_REQUEST = "ADD_CHAT_REQUEST";
export const ADD_CHAT_SUCCESS = "ADD_CHAT_SUCCESS";
export const ADD_CHAT_FAIL = "ADD_CHAT_FAIL";


export const CHATE_MESSAGES_LIST_REQUEST = "CHATE_MESSAGES_LIST_REQUEST";
export const CHATE_MESSAGES_LIST_SUCCESS = "CHATE_MESSAGES_LIST_SUCCESS";
export const CHATE_MESSAGES_LIST_FAIL = "CHATE_MESSAGES_LIST_FAIL";