export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAIL = "USER_LIST_FAIL"

export const USER_POSTS_LIST_REQUEST = "USER_POSTS_LIST_REQUEST"
export const USER_POSTS_LIST_SUCCESS = "USER_POSTS_LIST_SUCCESS"
export const USER_POSTS_LIST_FAIL = "USER_POSTS_LIST_FAIL"

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUES"
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS"
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL"

